org.gradle.jvmargs=-Xmx3G -Djava.net.preferIPv4Stack=true
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.java.installations.paths=/root/.local/share/mise/installs/java/17.0.2
org.gradle.java.installations.auto-download=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
curios_version=5.+
mod_id=megacurioschest
mod_name=Mega Curios Chest
mod_license=LGPL-3.0
mod_version=1.0.4
mod_authors=MegaCuriosChest
mod_description=A large portable curios chest with stackable trinkets and quick-equip.

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1
